version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: password
    restart: always
    ports:
      - "2000:2000"
    depends_on:
      - db

  server:
    build:
      context: server
      dockerfile: Dockerfile
    restart: always
    environment:

      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - db

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_URL: http://localhost:8080/auth 
      REACT_APP_REALM: react-realm 
      REACT_APP_CLIENTID: user 
    depends_on:
      - server

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      # must be the last one to start since has to redirect to those servicies
      - keycloak
      - server
      - client
      - db