version: '3'
services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql

  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: password
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db


  server:
    build:
      context: server
      dockerfile: Dockerfile
    restart: always
    environment:
      LOCALHOST_DOMAIN: fra.com # change it with your domain name
      REALM: react-realm
    ports:
      - "5000:5000"
    extra_hosts:
      - "fra.com:192.168.1.207" # change it in /etc/hosts with your domain and your ip addr

  client:
    build:
      context: client
      dockerfile: Dockerfile
    environment:
      REACT_APP_HOST_DOMAIN: fra.com # change it with your domain name
      REACT_APP_AUTH_SERVER_URL: http://fra.com:8080/auth # change it with your host
      REACT_APP_REALM: react-realm
      REACT_APP_CLIENTID: user
    ports:
      - "3000:3000"
    depends_on:
      - server
      - keycloak

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - keycloak
      - server
      - db
    extra_hosts:
      - "fra.com:192.168.1.207" # change it in /etc/hosts with your domain and your ip addr


volumes:
  db:

