apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      restartPolicy: Always
      containers:
      - name: keycloak
        image: jboss/keycloak

        env:
        - name: DB_PORT
          value: "5432"
        - name: KEYCLOAK_USER
          value: admin
        - name: DB_VENDOR
          value: POSTGRES
        - name: DB_ADDR
          value: postgres-service
        - name: DB_DATABASE
          value: keycloak
        - name: DB_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_PASSWORD
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
              
        resources:
          limits:
            memory: "650Mi"
            cpu: "550m"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer